---

- name: nginx container
  docker_container:
    name: nginx
    image: sdorra/nginx:1.11.8
    restart_policy: always
    networks:
    - name: network_one
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/lib/nginx:/etc/nginx:ro
    - /var/www:/var/www:ro
    log_driver: gelf
    log_options: 
      gelf-address: udp://localhost:12201
      tag: nginx
