---
- include: directories.yml
- include: auth.yml

- include: ssl-selfsigned.yml
  when: ssl_mode != "none"

- include: ssl-letsencrypt-main.yml
  when: ssl_mode == "letsencrypt"

- include: config.yml
- include: static-sites.yml
- include: metrics.yml
- include: proxy.yml
- include: container.yml
- include: ports.yml
