---

- name: create configuration directory
  file: 
    path: /var/lib/nginx
    state: directory

- include: auth.yml
- include: config.yml
- include: static-sites.yml
- include: metrics.yml
- include: proxy.yml
- include: container.yml
- include: ports.yml
