---
driver:
  name: vagrant
  network:
  - ["private_network", { ip: "192.168.42.42" }]
  customize:
    cpus: 2
    memory: "4096"
    natdnshostresolver1: "on"
    natdnsproxy1: "on"

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  playbook: playbook.yml
  roles_path: roles
  ansible_verbose: false
  ansible_version: latest
  require_chef_for_busser: true

platforms:
  - name: ubuntu-16.04
    box: bento/ubuntu-16.04

suites:
  - name: default
