---

- hosts: all
  user: vagrant
  become: yes
  gather_facts: yes
  vars:
  - test_mode: true
  - domain: example.net
  - admin:
      name: sdorra
      password: hallo123
  - static_sites:
    - name: example.com
    - name: www.example.net
  roles:
    - commons
    - docker
    - cadvisor
    - prometheus
    - elk
    - nginx
