---

- name: cadvisor container
  docker_container:
    name: cadvisor
    image: google/cadvisor:v0.24.1
    networks:
    - name: network_one
    restart_policy: always
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

- name: open port 8080
  ufw:
    rule: allow
    port: 8080
