---

- name: Install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - htop
  - ufw
  - openssh-server
  - unzip
  - python-pip
  - ntp

- name: Besure ntp is running
  service: 
    name: ntp
    state: running

- name: Besure ssh server is running
  service: 
    name: ssh 
    state: running

- name: Open ssh port
  ufw:
    rule: allow
    port: 22
