---

- name: kibana container
  docker_container:
    name: kibana
    image: kibana:5.1.1
    env:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    restart_policy: always
    networks:
    - name: network_one
