---

- name: kibana container
  docker_container:
    name: kibana
    image: kibana:{{ kibana_version }}
    env:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    restart_policy: always
    networks:
    - name: network_one
