---

- name: node-exporter container
  docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:v0.13.0
    restart_policy: always
    networks:
    - name: network_one
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    command:
    - -collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"

- name: prometheus directory
  file: 
    path: /var/lib/prometheus
    state: directory

- name: prometheus configuration
  copy:
    src: configuration.yml
    dest: /var/lib/prometheus/configuration.yml

- name: prometheus data directory
  file: 
    path: /var/lib/prometheus/data
    state: directory

- name: prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus:v1.4.1
    restart_policy: always
    networks:
    - name: network_one
    volumes:
    - /var/lib/prometheus/configuration.yml:/etc/prometheus/prometheus.yml:ro
    - /var/lib/prometheus/data:/prometheus-data

- name: grafana directory
  file: 
    path: /var/lib/grafana
    state: directory

- name: grafana container
  docker_container:
    name: grafana
    image: grafana/grafana:4.0.2
    restart_policy: always
    networks:
    - name: network_one
    volumes:
    - /var/lib/grafana:/var/lib/grafana
