---

- name: node-exporter container
  docker_container:
    name: node-exporter
    image: quay.io/prometheus/node-exporter:{{ node_exporter_version }}
    restart_policy: always
    networks:
    - name: network_one
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    command:
    - -collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"
