---
- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  register: add_repository_key

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present

- name: Install (or update) docker package
  apt:
    name: docker-engine
    state: present
  notify:
    - ensure docker is running

- name: Install pip
  apt:
    name: python-pip
    state: present

- name: Install docker py
  pip:
    name: "{{ item }}"
  with_items:
    - docker-py
    - docker-compose

- name: Create a network
  docker_network:
    name: "network_one"
